calibration:
  epochs: 1000
  patience: 50
  cal_lr: 0.01
  cal_weight_decay: 0
  num_bin: 10
  calibrator_name: WATS
  dist_to_train: ~
  heads: 2
  bias: 1
  cal_dropout: 0.2
  cal_hidden_dim: 32
gnn:
  type: gcn
  num_layer: 2
  hid_dim: 16
  dropout: 0.5
  norm: ~
train:
  epochs: 200
  lr: 1e-2
  weight_decay: 5e-4
  patience: 50
