calibration:
  epochs: 1000
  patience: 50
  cal_lr: 0.01
  cal_weight_decay: 0
  num_bin: 10
  calibrator_name: GTS
  dist_to_train: ~
  heads: 2
  bias: 1
  cal_dropout: 0.5
gnn:
  type: gcn
  num_layer: 2
  hid_dim: 64
  dropout: 0.8
  norm: ~
train:
  epochs: 200
  lr: 1e-2
  weight_decay: 1e-3
  patience: 50
